FORMAT: 1A

# Greetings API

This API is all about greetings.

## Greeting resource [/greeting]

### Retrive [GET]

+ Response 200 (application/json)

        [{
            "greeting:":"Hello world!"
        }]